#!/usr/bin/env python

from Tkinter import *
import sys
import os
import time
import random

class Person():

    population = 0
    inventory = []

    def __init__(self, name, age, item):
        self.name = name
        self.age = age
        self.item = item
        self.inventory.append(self.item.name)
        Person.population += 1

    def showpop(self):
        print(Person.population)

    def showinv(self):
        print(self.inventory)

class Item():

    items = 0

    def __init__(self, name, durability, decay, status):
        self.name = name
        self.durability = durability
        Item.items += 1

    def use(self):
        if self.durability < 0:
            self.status = 0
        else:
            print('Item is used')
            self.durability -= self.decay


def prompt():
    choice = raw_input('> ')
    return choice

def main():

    gun = Item('gun', 100, 3, 1)
    salman = Person('Salman', 18, gun)
    print("Welcome " + salman.name + "!\n\n");
    print("Type 'begin' to start your life...");


    while 1:
        a = prompt()
        break


main()
